enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: "Gov Shared Services"
  - name: SharedServices
  - name: "Gov Shared Services/Gov Management"
    ignore: true
serviceControlPolicies: []
# Ensured the values of the tag matching the required value
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Root
chatbotPolicies: []
backupPolicies: []
