enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Gov Management
    ignore: true
serviceControlPolicies: []
taggingPolicies: []
chatbotPolicies: []
backupPolicies: []