enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: "Gov Shared Services"
  - name: "Gov Shared Services/Gov Management"
    ignore: true
serviceControlPolicies: []
taggingPolicies: []
chatbotPolicies: []
backupPolicies: []
