centralSecurityServices:
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: true
    excludeRegions: []
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
  scpRevertChangesConfig:
    enable: false
  snsSubscriptions: []
  macie:
    enable: false
    excludeRegions: []
    policyFindingsPublishingFrequency: FIFTEEN_MINUTES
    publishSensitiveDataFindings: false
  guardduty:
    enable: true
    excludeRegions: []
    s3Protection:
      enable: true
      excludeRegions: []
    exportConfiguration:
      enable: false
      overrideExisting: false
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
  securityHub:
    enable: true
    regionAggregation: false
    excludeRegions: []
    standards: 
      - name: AWS Foundational Security Best Practices v1.0.0
        enable: true
      - name: CIS AWS Foundations Benchmark v1.2.0
        enable: true
  ssmAutomation:
    excludeRegions: []
    documentSets:
      - shareTargets:
          organizationalUnits:
            - Root
        documents:
          # Enforces Tagging
          - name: S3-Enforce-Tagging
            template: ssm-documents/s3/s3-required-tags.yaml
accessAnalyzer:
  enable: true
iamPasswordPolicy:
  allowUsersToChangePassword: true
  hardExpiry: false
  requireUppercaseCharacters: true
  requireLowercaseCharacters: true
  requireSymbols: true
  requireNumbers: true
  minimumPasswordLength: 14
  passwordReusePrevention: 24
  maxPasswordAge: 90
awsConfig:
  enableConfigurationRecorder: true
  ruleSets:
    - deploymentTargets:
        organizationalUnits:
          - Root
      rules:
  ##################################################################################################################
  # Data Classification and tagging                                                                             #
  ##################################################################################################################
        - name: m1-tagging-s3-bucket-required-tags-remediate
          identifier: REQUIRED_TAGS
          complianceResourceTypes:
            - AWS::S3::Bucket
          inputParameters:
            tag1Key: "DataClassification"
          remediation:
            rolePolicyFile: custom-config-rules/roles/m1-bucket-enforce-required-tags.json
            automatic: true
            targetId: S3-Enforce-Tagging
            retryAttemptSeconds: 60
            maximumAutomaticAttempts: 5
            parameters:
              - name: BucketName
                value: RESOURCE_ID
                type: String
              - name: TagKey
                value: DataClassification
                type: String
              - name: TagValue
                value: CompanyConfidential
                type: String
# Checks if your resources have the tags that you specify
        - name: m1-tagging-required-tags
          identifier: REQUIRED_TAGS
          complianceResourceTypes:
            - AWS::ACM::Certificate
            - AWS::AutoScaling::AutoScalingGroup
            - AWS::CloudFormation::Stack
            - AWS::CodeBuild::Project
            - AWS::DynamoDB::Table
            - AWS::EC2::CustomerGateway
            - AWS::EC2::Instance
            - AWS::EC2::InternetGateway
            - AWS::EC2::NetworkAcl
            - AWS::EC2::NetworkInterface
            - AWS::EC2::RouteTable
            - AWS::EC2::SecurityGroup
            - AWS::EC2::Subnet
            - AWS::EC2::Volume
            - AWS::EC2::VPC
            - AWS::EC2::VPNConnection
            - AWS::EC2::VPNGateway
            - AWS::ElasticLoadBalancing::LoadBalancer
            - AWS::ElasticLoadBalancingV2::LoadBalancer
            - AWS::RDS::DBInstance
            - AWS::RDS::DBSecurityGroup
            - AWS::RDS::DBSnapshot
            - AWS::RDS::DBSubnetGroup
            - AWS::RDS::EventSubscription
            - AWS::Redshift::Cluster
            - AWS::Redshift::ClusterParameterGroup
            - AWS::Redshift::ClusterSecurityGroup
            - AWS::Redshift::ClusterSnapshot
            - AWS::Redshift::ClusterSubnetGroup
            - AWS::S3::Bucket
          inputParameters:
            tag1Key: DataClassification
cloudWatch:
  metricSets: []
  alarmSets: []
keyManagementService:
  keySets: []